# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auto_auction_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auto_auction_rpc.proto',
  package='auction',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x61uto_auction_rpc.proto\x12\x07\x61uction\"\x94\x01\n\x0b\x41utoRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08req_type\x18\x03 \x01(\t\x12$\n\x02pv\x18\x04 \x01(\x0b\x32\x18.auction.PurchaseVehicle\x12&\n\x06youxin\x18\x05 \x01(\x0b\x32\x16.auction.YouXinRequest\"\x81\x01\n\x0c\x41utoResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08\x65rr_code\x18\x03 \x01(\t\x12\x0f\n\x07\x65rr_msg\x18\x04 \x01(\t\x12\'\n\x06youxin\x18\x05 \x01(\x0b\x32\x17.auction.YouXinResponse\"\xd3\x01\n\rYouXinRequest\x12\x12\n\nvehicle_id\x18\x04 \x01(\t\x12\x1b\n\x13\x63urrent_total_price\x18\x05 \x01(\x02\x12\x1b\n\x13\x63urrent_quote_price\x18\x06 \x01(\x02\x12\r\n\x05steps\x18\x07 \x03(\x03\x12\x16\n\x0eis_first_price\x18\x08 \x01(\x08\x12\x1f\n\x17is_arrive_reserve_price\x18\t \x01(\x03\x12\x17\n\x0fmax_total_price\x18\n \x01(\x02\x12\x13\n\x0b\x64\x65\x61l_status\x18\x0b \x01(\t\"M\n\x0eYouXinResponse\x12\x12\n\nis_auction\x18\x03 \x01(\x08\x12\x0c\n\x04step\x18\x04 \x01(\x03\x12\x19\n\x11\x61\x66ter_quote_price\x18\x05 \x01(\x02\"\xae\x01\n\x0fPurchaseVehicle\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nvehicle_id\x18\x02 \x01(\t\x12\x19\n\x11\x65xpect_full_price\x18\x03 \x01(\x02\x12\x1e\n\x16\x65xpect_financial_price\x18\x04 \x01(\x02\x12!\n\x19\x65xpect_purchase_price_max\x18\x05 \x01(\x02\x12\x1d\n\x15\x65xpect_purchase_price\x18\x06 \x01(\x02\x32K\n\x0b\x41utoAuction\x12<\n\x07\x61uction\x12\x14.auction.AutoRequest\x1a\x15.auction.AutoResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)




_AUTOREQUEST = _descriptor.Descriptor(
  name='AutoRequest',
  full_name='auction.AutoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='auction.AutoRequest.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='auction.AutoRequest.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_type', full_name='auction.AutoRequest.req_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pv', full_name='auction.AutoRequest.pv', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='youxin', full_name='auction.AutoRequest.youxin', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=184,
)


_AUTORESPONSE = _descriptor.Descriptor(
  name='AutoResponse',
  full_name='auction.AutoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='auction.AutoResponse.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='auction.AutoResponse.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_code', full_name='auction.AutoResponse.err_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='auction.AutoResponse.err_msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='youxin', full_name='auction.AutoResponse.youxin', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=316,
)


_YOUXINREQUEST = _descriptor.Descriptor(
  name='YouXinRequest',
  full_name='auction.YouXinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehicle_id', full_name='auction.YouXinRequest.vehicle_id', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_total_price', full_name='auction.YouXinRequest.current_total_price', index=1,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_quote_price', full_name='auction.YouXinRequest.current_quote_price', index=2,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steps', full_name='auction.YouXinRequest.steps', index=3,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_first_price', full_name='auction.YouXinRequest.is_first_price', index=4,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_arrive_reserve_price', full_name='auction.YouXinRequest.is_arrive_reserve_price', index=5,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_total_price', full_name='auction.YouXinRequest.max_total_price', index=6,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deal_status', full_name='auction.YouXinRequest.deal_status', index=7,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=530,
)


_YOUXINRESPONSE = _descriptor.Descriptor(
  name='YouXinResponse',
  full_name='auction.YouXinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_auction', full_name='auction.YouXinResponse.is_auction', index=0,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='auction.YouXinResponse.step', index=1,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='after_quote_price', full_name='auction.YouXinResponse.after_quote_price', index=2,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=609,
)


_PURCHASEVEHICLE = _descriptor.Descriptor(
  name='PurchaseVehicle',
  full_name='auction.PurchaseVehicle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='auction.PurchaseVehicle.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vehicle_id', full_name='auction.PurchaseVehicle.vehicle_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expect_full_price', full_name='auction.PurchaseVehicle.expect_full_price', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expect_financial_price', full_name='auction.PurchaseVehicle.expect_financial_price', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expect_purchase_price_max', full_name='auction.PurchaseVehicle.expect_purchase_price_max', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expect_purchase_price', full_name='auction.PurchaseVehicle.expect_purchase_price', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=612,
  serialized_end=786,
)

_AUTOREQUEST.fields_by_name['pv'].message_type = _PURCHASEVEHICLE
_AUTOREQUEST.fields_by_name['youxin'].message_type = _YOUXINREQUEST
_AUTORESPONSE.fields_by_name['youxin'].message_type = _YOUXINRESPONSE
DESCRIPTOR.message_types_by_name['AutoRequest'] = _AUTOREQUEST
DESCRIPTOR.message_types_by_name['AutoResponse'] = _AUTORESPONSE
DESCRIPTOR.message_types_by_name['YouXinRequest'] = _YOUXINREQUEST
DESCRIPTOR.message_types_by_name['YouXinResponse'] = _YOUXINRESPONSE
DESCRIPTOR.message_types_by_name['PurchaseVehicle'] = _PURCHASEVEHICLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AutoRequest = _reflection.GeneratedProtocolMessageType('AutoRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTOREQUEST,
  __module__ = 'auto_auction_rpc_pb2'
  # @@protoc_insertion_point(class_scope:auction.AutoRequest)
  ))
_sym_db.RegisterMessage(AutoRequest)

AutoResponse = _reflection.GeneratedProtocolMessageType('AutoResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTORESPONSE,
  __module__ = 'auto_auction_rpc_pb2'
  # @@protoc_insertion_point(class_scope:auction.AutoResponse)
  ))
_sym_db.RegisterMessage(AutoResponse)

YouXinRequest = _reflection.GeneratedProtocolMessageType('YouXinRequest', (_message.Message,), dict(
  DESCRIPTOR = _YOUXINREQUEST,
  __module__ = 'auto_auction_rpc_pb2'
  # @@protoc_insertion_point(class_scope:auction.YouXinRequest)
  ))
_sym_db.RegisterMessage(YouXinRequest)

YouXinResponse = _reflection.GeneratedProtocolMessageType('YouXinResponse', (_message.Message,), dict(
  DESCRIPTOR = _YOUXINRESPONSE,
  __module__ = 'auto_auction_rpc_pb2'
  # @@protoc_insertion_point(class_scope:auction.YouXinResponse)
  ))
_sym_db.RegisterMessage(YouXinResponse)

PurchaseVehicle = _reflection.GeneratedProtocolMessageType('PurchaseVehicle', (_message.Message,), dict(
  DESCRIPTOR = _PURCHASEVEHICLE,
  __module__ = 'auto_auction_rpc_pb2'
  # @@protoc_insertion_point(class_scope:auction.PurchaseVehicle)
  ))
_sym_db.RegisterMessage(PurchaseVehicle)



_AUTOAUCTION = _descriptor.ServiceDescriptor(
  name='AutoAuction',
  full_name='auction.AutoAuction',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=788,
  serialized_end=863,
  methods=[
  _descriptor.MethodDescriptor(
    name='auction',
    full_name='auction.AutoAuction.auction',
    index=0,
    containing_service=None,
    input_type=_AUTOREQUEST,
    output_type=_AUTORESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTOAUCTION)

DESCRIPTOR.services_by_name['AutoAuction'] = _AUTOAUCTION

# @@protoc_insertion_point(module_scope)
