# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auto_auction_abi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auto_auction_abi.proto',
  package='auction',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x61uto_auction_abi.proto\x12\x07\x61uction\"n\n\x0b\x41utoRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08req_type\x18\x03 \x01(\t\x12&\n\x06youxin\x18\x04 \x01(\x0b\x32\x16.auction.YouXinRequest\"\x81\x01\n\x0c\x41utoResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08\x65rr_code\x18\x03 \x01(\t\x12\x0f\n\x07\x65rr_msg\x18\x04 \x01(\t\x12\'\n\x06youxin\x18\x05 \x01(\x0b\x32\x17.auction.YouXinResponse\"\xa5\x01\n\rYouXinRequest\x12\x12\n\nvehicle_id\x18\x04 \x01(\t\x12\x1b\n\x13\x63urrent_total_price\x18\x05 \x01(\x02\x12\x1b\n\x13\x63urrent_quote_price\x18\x06 \x01(\x02\x12\r\n\x05steps\x18\x07 \x03(\x03\x12\x16\n\x0eis_first_price\x18\x08 \x01(\x08\x12\x1f\n\x17is_arrive_reserve_price\x18\t \x01(\x03\"M\n\x0eYouXinResponse\x12\x12\n\nis_auction\x18\x03 \x01(\x08\x12\x0c\n\x04step\x18\x04 \x01(\x03\x12\x19\n\x11\x61\x66ter_total_price\x18\x05 \x01(\x02\x62\x06proto3')
)




_AUTOREQUEST = _descriptor.Descriptor(
  name='AutoRequest',
  full_name='auction.AutoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='auction.AutoRequest.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='auction.AutoRequest.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req_type', full_name='auction.AutoRequest.req_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='youxin', full_name='auction.AutoRequest.youxin', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=145,
)


_AUTORESPONSE = _descriptor.Descriptor(
  name='AutoResponse',
  full_name='auction.AutoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='auction.AutoResponse.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='auction.AutoResponse.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_code', full_name='auction.AutoResponse.err_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='auction.AutoResponse.err_msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='youxin', full_name='auction.AutoResponse.youxin', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=277,
)


_YOUXINREQUEST = _descriptor.Descriptor(
  name='YouXinRequest',
  full_name='auction.YouXinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehicle_id', full_name='auction.YouXinRequest.vehicle_id', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_total_price', full_name='auction.YouXinRequest.current_total_price', index=1,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_quote_price', full_name='auction.YouXinRequest.current_quote_price', index=2,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steps', full_name='auction.YouXinRequest.steps', index=3,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_first_price', full_name='auction.YouXinRequest.is_first_price', index=4,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_arrive_reserve_price', full_name='auction.YouXinRequest.is_arrive_reserve_price', index=5,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=445,
)


_YOUXINRESPONSE = _descriptor.Descriptor(
  name='YouXinResponse',
  full_name='auction.YouXinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_auction', full_name='auction.YouXinResponse.is_auction', index=0,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='auction.YouXinResponse.step', index=1,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='after_total_price', full_name='auction.YouXinResponse.after_total_price', index=2,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=524,
)

_AUTOREQUEST.fields_by_name['youxin'].message_type = _YOUXINREQUEST
_AUTORESPONSE.fields_by_name['youxin'].message_type = _YOUXINRESPONSE
DESCRIPTOR.message_types_by_name['AutoRequest'] = _AUTOREQUEST
DESCRIPTOR.message_types_by_name['AutoResponse'] = _AUTORESPONSE
DESCRIPTOR.message_types_by_name['YouXinRequest'] = _YOUXINREQUEST
DESCRIPTOR.message_types_by_name['YouXinResponse'] = _YOUXINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AutoRequest = _reflection.GeneratedProtocolMessageType('AutoRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTOREQUEST,
  __module__ = 'auto_auction_abi_pb2'
  # @@protoc_insertion_point(class_scope:auction.AutoRequest)
  ))
_sym_db.RegisterMessage(AutoRequest)

AutoResponse = _reflection.GeneratedProtocolMessageType('AutoResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTORESPONSE,
  __module__ = 'auto_auction_abi_pb2'
  # @@protoc_insertion_point(class_scope:auction.AutoResponse)
  ))
_sym_db.RegisterMessage(AutoResponse)

YouXinRequest = _reflection.GeneratedProtocolMessageType('YouXinRequest', (_message.Message,), dict(
  DESCRIPTOR = _YOUXINREQUEST,
  __module__ = 'auto_auction_abi_pb2'
  # @@protoc_insertion_point(class_scope:auction.YouXinRequest)
  ))
_sym_db.RegisterMessage(YouXinRequest)

YouXinResponse = _reflection.GeneratedProtocolMessageType('YouXinResponse', (_message.Message,), dict(
  DESCRIPTOR = _YOUXINRESPONSE,
  __module__ = 'auto_auction_abi_pb2'
  # @@protoc_insertion_point(class_scope:auction.YouXinResponse)
  ))
_sym_db.RegisterMessage(YouXinResponse)


# @@protoc_insertion_point(module_scope)
