# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auto_auction_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import auto_auction_abi_pb2 as auto__auction__abi__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='auto_auction_rpc.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x61uto_auction_rpc.proto\x1a\x16\x61uto_auction_abi.proto2J\n\x0e\x41uctionService\x12\x38\n\x07\x61uction\x12\x14.auction.AutoRequest\x1a\x15.auction.AutoResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[auto__auction__abi__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_AUCTIONSERVICE = _descriptor.ServiceDescriptor(
  name='AuctionService',
  full_name='AuctionService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=50,
  serialized_end=124,
  methods=[
  _descriptor.MethodDescriptor(
    name='auction',
    full_name='AuctionService.auction',
    index=0,
    containing_service=None,
    input_type=auto__auction__abi__pb2._AUTOREQUEST,
    output_type=auto__auction__abi__pb2._AUTORESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUCTIONSERVICE)

DESCRIPTOR.services_by_name['AuctionService'] = _AUCTIONSERVICE

# @@protoc_insertion_point(module_scope)
