# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigmob_jion.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from learngrpc.proto import sigmob_rtb_pb2 as sigmob__rtb__pb2
from learngrpc.proto import sigmob_ad_operation_pb2 as sigmob__ad__operation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sigmob_jion.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11sigmob_jion.proto\x1a\x10sigmob_rtb.proto\x1a\x19sigmob_ad_operation.proto\"\xbd\x02\n\tSearchLog\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x15\n\rtime_interval\x18\x03 \x01(\r\x12\x0b\n\x03uid\x18\x04 \x01(\t\x12\x12\n\nchannel_id\x18\x05 \x01(\t\x12#\n\x07request\x18\x06 \x01(\x0b\x32\x12.sigmob.BidRequest\x12%\n\x08response\x18\x07 \x01(\x0b\x32\x13.sigmob.BidResponse\x12\x12\n\nerror_code\x18\x08 \x01(\x04\x12\x17\n\x0fprocess_time_ms\x18\t \x01(\x04\x12$\n\rindex_request\x18\n \x01(\x0b\x32\r.IndexRequest\x12&\n\x0eindex_response\x18\x0b \x01(\x0b\x32\x0e.IndexResponse\x12\x11\n\tserver_ip\x18\x0c \x01(\t\"/\n\x0cIndexRequest\x12\x1f\n\x06groups\x18\x01 \x03(\x0b\x32\x0f.IndexTermGroup\"O\n\rIndexResponse\x12\x16\n\x0elookup_ad_list\x18\x01 \x03(\t\x12&\n\tvalid_ads\x18\x02 \x03(\x0b\x32\x13.operation.Campaign\"$\n\x0eIndexTermGroup\x12\x12\n\nindex_term\x18\x01 \x03(\t2.\n\x03Rtb\x12\'\n\x0bGetMobileAd\x12\n.SearchLog\x1a\n.SearchLog\"\x00\x42\x12\n\tcom.entryZ\x05\x65ntryb\x06proto3')
  ,
  dependencies=[sigmob__rtb__pb2.DESCRIPTOR,sigmob__ad__operation__pb2.DESCRIPTOR,])




_SEARCHLOG = _descriptor.Descriptor(
  name='SearchLog',
  full_name='SearchLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sid', full_name='SearchLog.sid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SearchLog.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_interval', full_name='SearchLog.time_interval', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='SearchLog.uid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='SearchLog.channel_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='SearchLog.request', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='SearchLog.response', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='SearchLog.error_code', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process_time_ms', full_name='SearchLog.process_time_ms', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_request', full_name='SearchLog.index_request', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_response', full_name='SearchLog.index_response', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_ip', full_name='SearchLog.server_ip', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=384,
)


_INDEXREQUEST = _descriptor.Descriptor(
  name='IndexRequest',
  full_name='IndexRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groups', full_name='IndexRequest.groups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=433,
)


_INDEXRESPONSE = _descriptor.Descriptor(
  name='IndexResponse',
  full_name='IndexResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lookup_ad_list', full_name='IndexResponse.lookup_ad_list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_ads', full_name='IndexResponse.valid_ads', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=514,
)


_INDEXTERMGROUP = _descriptor.Descriptor(
  name='IndexTermGroup',
  full_name='IndexTermGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index_term', full_name='IndexTermGroup.index_term', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=552,
)

_SEARCHLOG.fields_by_name['request'].message_type = sigmob__rtb__pb2._BIDREQUEST
_SEARCHLOG.fields_by_name['response'].message_type = sigmob__rtb__pb2._BIDRESPONSE
_SEARCHLOG.fields_by_name['index_request'].message_type = _INDEXREQUEST
_SEARCHLOG.fields_by_name['index_response'].message_type = _INDEXRESPONSE
_INDEXREQUEST.fields_by_name['groups'].message_type = _INDEXTERMGROUP
_INDEXRESPONSE.fields_by_name['valid_ads'].message_type = sigmob__ad__operation__pb2._CAMPAIGN
DESCRIPTOR.message_types_by_name['SearchLog'] = _SEARCHLOG
DESCRIPTOR.message_types_by_name['IndexRequest'] = _INDEXREQUEST
DESCRIPTOR.message_types_by_name['IndexResponse'] = _INDEXRESPONSE
DESCRIPTOR.message_types_by_name['IndexTermGroup'] = _INDEXTERMGROUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchLog = _reflection.GeneratedProtocolMessageType('SearchLog', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHLOG,
  __module__ = 'sigmob_jion_pb2'
  # @@protoc_insertion_point(class_scope:SearchLog)
  ))
_sym_db.RegisterMessage(SearchLog)

IndexRequest = _reflection.GeneratedProtocolMessageType('IndexRequest', (_message.Message,), dict(
  DESCRIPTOR = _INDEXREQUEST,
  __module__ = 'sigmob_jion_pb2'
  # @@protoc_insertion_point(class_scope:IndexRequest)
  ))
_sym_db.RegisterMessage(IndexRequest)

IndexResponse = _reflection.GeneratedProtocolMessageType('IndexResponse', (_message.Message,), dict(
  DESCRIPTOR = _INDEXRESPONSE,
  __module__ = 'sigmob_jion_pb2'
  # @@protoc_insertion_point(class_scope:IndexResponse)
  ))
_sym_db.RegisterMessage(IndexResponse)

IndexTermGroup = _reflection.GeneratedProtocolMessageType('IndexTermGroup', (_message.Message,), dict(
  DESCRIPTOR = _INDEXTERMGROUP,
  __module__ = 'sigmob_jion_pb2'
  # @@protoc_insertion_point(class_scope:IndexTermGroup)
  ))
_sym_db.RegisterMessage(IndexTermGroup)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\tcom.entryZ\005entry'))

_RTB = _descriptor.ServiceDescriptor(
  name='Rtb',
  full_name='Rtb',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=554,
  serialized_end=600,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMobileAd',
    full_name='Rtb.GetMobileAd',
    index=0,
    containing_service=None,
    input_type=_SEARCHLOG,
    output_type=_SEARCHLOG,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RTB)

DESCRIPTOR.services_by_name['Rtb'] = _RTB

# @@protoc_insertion_point(module_scope)
